### ISSUE TITLE
Sequences in final fasta files do not match OTUs and ESVs in xlsx files.

### ISSUE THREAD

**Issue by AlvaroFueyo** [DominikBuchner/apscale#11]
The sequences in the xlsx files do not match those in the fasta files. This results in the taxonomic assignment of either local or ncbi blasts in apscale_gui not matching their OTU or ESV number.

O.S: Windows 11
Library: 12S and COI
VSearch version: 2.20.0
Python version: 3.9.13

**Comment by DominikBuchner** [comment]
Fixed with version 1.7.0
