### ISSUE TITLE
PCR replicate consistency merging in APSCALE

### ISSUE THREAD

**Issue by AlvaroFueyo** [DominikBuchner/apscale#12]
The slowest step in the metabarcoding pipeline is the taxonomic assignment, and reducing the number of OTUs or ESVs could reduce the workload of this step. Therefore, a new final step could be added to the APSCALE pipeline, PCR replicate consistency merging.

**Comment by DominikBuchner** [comment]
This is to complicated to add, not all labs use exactly two replicates and differing appendixes to indicate their replicates. What about extraction vs. PCR replicates? To keep the software open for a wide userbase (not only people who use our workflow, although I'd recommend that) I won't add this, but suggest users to use custom solutions.
