### ISSUE TITLE
vsearch: unrecognized option '--fastx_uniques'

### ISSUE THREAD

**Issue by panstrongylus** [DominikBuchner/apscale#8]
Hello,

apscale seems to be invoking an option that does not exist - is there a work around for this ? 

vsearch: unrecognized option '--fastx_uniques'

Many thanks

martin

**Comment by DominikBuchner** [comment]
Hi Martin,

The command was added with one of the latest updates. Please update your
vsearch to the latest version.

Best Dominik

panstrongylus ***@***.***> schrieb am Do., 18. Mai 2023,
15:10:

**Comment by panstrongylus** [comment]
Thanks ! Brilliant

**Comment by DominikBuchner** [comment]
Happy to help, let me know if any further question arise :)
