### ISSUE TITLE
Have problems with PE_merging

### ISSUE THREAD

**Issue by pvannucchi** [DominikBuchner/apscale#9]
Hello, I'm new to the program and I'm trying to analyze some fastq files I jusr received. Reads are already demultiplexed, so I put them in the 2_Demultiplexing folder. Whenever I try to merge PE reads I get this error message:
09:32:42: Finding all file pairs in your input. This may take a while.
09:32:42: Found 1 matching file pairs in 2 input files.
09:32:42: Starting to merge forward and reverse reads.
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "c:\users\pvannucchi\appdata\local\programs\python\python39\lib\site-packages\joblib\externals\loky\process_executor.py", line 463, in _process_worker
    r = call_item()
  File "c:\users\pvannucchi\appdata\local\programs\python\python39\lib\site-packages\joblib\externals\loky\process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "c:\users\pvannucchi\appdata\local\programs\python\python39\lib\site-packages\joblib\parallel.py", line 589, in __call__
    return [func(*args, **kwargs)
  File "c:\users\pvannucchi\appdata\local\programs\python\python39\lib\site-packages\joblib\parallel.py", line 589, in <listcomp>
    return [func(*args, **kwargs)
  File "c:\users\pvannucchi\appdata\local\programs\python\python39\lib\site-packages\apscale\b_pe_merging.py", line 73, in pe_merge
    re.findall("(\d+)  Pairs", content)[0],
IndexError: list index out of range

Could you please indicate me how I could fix this problem?
Thank you in advance.

**Comment by DominikBuchner** [comment]
Can you please check your vsearch version?

**Comment by pvannucchi** [comment]
Hi Dominik,

I was able to fix the problem (I just had to copy de dll file into the new vsearch folder again) and now with the downgraded version of Vsearch, it works!

Thank you so much for your help.

Cheers,

Patrizia Elena Vannucchi
Área Ecología Acuática
Eurofins Cavendish, S.L.U.
Ctra. Bailén-Motril, parc. 102 B, Edif. Cristal 2, Pol. Juncaril
C.P.: 18210 – Peligros (Granada)
Spain
Phone: +34 663701104

Email: ***@***.******@***.***>
Website: https://www.eurofins-environment.es/es/eurofins-cavendish/
Política de privacidad<https://www.eurofins-environment.es/es/politica-privacidad/>
***@***.***

¡Síguenos en LinkedIn!
[Logo Linkedin Transparente - Vectores y PSD gratuitos para descargar]<https://es.linkedin.com/company/eurofins-cavendish>

This e-mail including its attachments may contain confidential and proprietary information. Any unauthorized disclosure or use of this e-mail including its attachments is prohibited and may be prosecuted. If you are not the intended recipient, please inform the sender by an e-mail reply and delete the message.
Transmission by e-mail is not secure and can result in errors or omissions in the content of the message. Despite state-of-the-art precautions we cannot guarantee that e-mails and attachments are free from viruses. We accept no liability for viruses or any transmission-related errors and omissions. You need to always virus-check any e-mails and attachments.
Eurofins companies are independent legal entities that are bound only by members of their management bodies. No other persons have representation power unless specifically authorised by proxy or other legal means.


De: DominikBuchner ***@***.***>
Enviado el: domingo, 17 de septiembre de 2023 21:29
Para: DominikBuchner/apscale ***@***.***>
CC: Patrizia Elena Vannucchi ***@***.***>; Author ***@***.***>
Asunto: Re: [DominikBuchner/apscale] Have problems with PE_merging (Issue #9)


Can you please check your vsearch version?
